import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const CommonLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <div className='gap-2 text-gray-800 h-full'>
    <nav className='h-14 border-b-2 border-b-slate-300 '>
      <div className='p-4 flex items-center justify-between'>
        <h1>Common Layout</h1>
        <ul className='flex gap-4 '>
          <li>
            <a href='/'>Home</a>
          </li>
          <li>
            <a href='/about'>About</a>
          </li>
        </ul>
      </div>
    </nav>
    {children}
  </div>
);

export default CommonLayout;
